export type Collocation = {
  id: number;
  vi: string;
  en: string;
  topic: string;
  kind?: "verb-pattern" | "preposition" | "speaking";
  pattern?: string;
  note?: string;
  chunkStep?: number;
};

const baseCollocations: Collocation[] = [
  { id: 1, vi: "Ngồi tại bàn", en: "be seated at a table", topic: "Miêu tả tranh" },
  { id: 2, vi: "Đứng xếp hàng", en: "be standing in line", topic: "Miêu tả tranh" },
  { id: 3, vi: "Đi bộ qua đường", en: "walk across the street", topic: "Miêu tả tranh" },
  { id: 4, vi: "Nhìn vào màn hình", en: "look at a screen", topic: "Miêu tả tranh" },
  { id: 5, vi: "Trò chuyện với nhau", en: "talk to each other", topic: "Miêu tả tranh" },
  { id: 6, vi: "Cầm trên tay", en: "hold something in one’s hand", topic: "Miêu tả tranh" },
  { id: 7, vi: "Làm việc trên máy tính", en: "work on a computer", topic: "Miêu tả tranh" },
  { id: 8, vi: "Ghi chép", en: "take notes", topic: "Miêu tả tranh" },
  { id: 9, vi: "Đặt vật gì lên bàn", en: "place something on a table", topic: "Miêu tả tranh" },
  { id: 10, vi: "Được trưng bày", en: "be on display", topic: "Miêu tả tranh" },
  { id: 11, vi: "Được sắp xếp trên kệ", en: "be arranged on shelves", topic: "Miêu tả tranh" },
  { id: 12, vi: "Đông nghịt người", en: "be crowded with people", topic: "Miêu tả tranh" },
  { id: 13, vi: "Ở tiền cảnh", en: "in the foreground", topic: "Miêu tả tranh" },
  { id: 14, vi: "Ở hậu cảnh", en: "in the background", topic: "Miêu tả tranh" },
  { id: 15, vi: "Bên cạnh nhau", en: "next to each other", topic: "Miêu tả tranh" },
  { id: 16, vi: "Ở giữa căn phòng", en: "in the middle of the room", topic: "Miêu tả tranh" },
  { id: 17, vi: "Ở ngoài trời", en: "in the open air", topic: "Miêu tả tranh" },
  { id: 18, vi: "Đeo kính", en: "wear glasses", topic: "Miêu tả tranh" },
  { id: 19, vi: "Mặc đồng phục", en: "wear a uniform", topic: "Miêu tả tranh" },
  { id: 20, vi: "Hướng mặt về phía máy ảnh", en: "face the camera", topic: "Miêu tả tranh" },

  { id: 21, vi: "Gửi yêu cầu", en: "submit a request", topic: "Email & yêu cầu" },
  { id: 22, vi: "Yêu cầu thông tin", en: "request information", topic: "Email & yêu cầu" },
  { id: 23, vi: "Cung cấp thêm thông tin", en: "provide additional information", topic: "Email & yêu cầu" },
  { id: 24, vi: "Xác nhận đã nhận", en: "confirm receipt", topic: "Email & yêu cầu" },
  { id: 25, vi: "Đính kèm một tệp", en: "attach a file", topic: "Email & yêu cầu" },
  { id: 26, vi: "Đặt lịch hẹn", en: "schedule an appointment", topic: "Email & yêu cầu" },
  { id: 27, vi: "Dời lịch hẹn", en: "reschedule an appointment", topic: "Email & yêu cầu" },
  { id: 28, vi: "Hủy lịch hẹn", en: "cancel an appointment", topic: "Email & yêu cầu" },
  { id: 29, vi: "Thông báo trước", en: "notify someone in advance", topic: "Email & yêu cầu" },
  { id: 30, vi: "Phản hồi kịp thời", en: "respond promptly", topic: "Email & yêu cầu" },
  { id: 31, vi: "Xin lỗi vì sự bất tiện", en: "apologize for the inconvenience", topic: "Email & yêu cầu" },
  { id: 32, vi: "Cảm ơn sự kiên nhẫn", en: "thank someone for their patience", topic: "Email & yêu cầu" },
  { id: 33, vi: "Giải quyết mối lo ngại", en: "address a concern", topic: "Email & yêu cầu" },
  { id: 34, vi: "Nêu lên mối lo ngại", en: "raise a concern", topic: "Email & yêu cầu" },
  { id: 35, vi: "Đưa ra phản hồi", en: "provide feedback", topic: "Email & yêu cầu" },
  { id: 36, vi: "Yêu cầu hỗ trợ", en: "request assistance", topic: "Email & yêu cầu" },
  { id: 37, vi: "Cung cấp sự hỗ trợ", en: "provide assistance", topic: "Email & yêu cầu" },
  { id: 38, vi: "Sớm nhất có thể", en: "at your earliest convenience", topic: "Email & yêu cầu" },
  { id: 39, vi: "Mong nhận được phản hồi", en: "look forward to hearing from you", topic: "Email & yêu cầu" },
  { id: 40, vi: "Đừng ngần ngại liên hệ", en: "do not hesitate to contact us", topic: "Email & yêu cầu" },
  { id: 41, vi: "Cập nhật thông tin cho ai", en: "keep someone informed", topic: "Email & yêu cầu" },
  { id: 42, vi: "Thực hiện những sắp xếp cần thiết", en: "make the necessary arrangements", topic: "Email & yêu cầu" },
  { id: 43, vi: "Xin phê duyệt", en: "request approval", topic: "Email & yêu cầu" },
  { id: 44, vi: "Nhận được sự phê duyệt", en: "receive approval", topic: "Email & yêu cầu" },
  { id: 45, vi: "Theo dõi một yêu cầu", en: "follow up on a request", topic: "Email & yêu cầu" },

  { id: 46, vi: "Đáp ứng thời hạn", en: "meet a deadline", topic: "Công việc & cuộc họp" },
  { id: 47, vi: "Lỡ thời hạn", en: "miss a deadline", topic: "Công việc & cuộc họp" },
  { id: 48, vi: "Đúng tiến độ", en: "on schedule", topic: "Công việc & cuộc họp" },
  { id: 49, vi: "Trước tiến độ", en: "ahead of schedule", topic: "Công việc & cuộc họp" },
  { id: 50, vi: "Chậm tiến độ", en: "behind schedule", topic: "Công việc & cuộc họp" },
  { id: 51, vi: "Tham dự cuộc họp", en: "attend a meeting", topic: "Công việc & cuộc họp" },
  { id: 52, vi: "Tổ chức cuộc họp", en: "hold a meeting", topic: "Công việc & cuộc họp" },
  { id: 53, vi: "Ghi biên bản cuộc họp", en: "take meeting minutes", topic: "Công việc & cuộc họp" },
  { id: 54, vi: "Đưa ra quyết định", en: "make a decision", topic: "Công việc & cuộc họp" },
  { id: 55, vi: "Đạt được thỏa thuận", en: "reach an agreement", topic: "Công việc & cuộc họp" },
  { id: 56, vi: "Chịu trách nhiệm", en: "take responsibility", topic: "Công việc & cuộc họp" },
  { id: 57, vi: "Chịu trách nhiệm về", en: "be responsible for", topic: "Công việc & cuộc họp" },
  { id: 58, vi: "Phụ trách", en: "be in charge of", topic: "Công việc & cuộc họp" },
  { id: 59, vi: "Hoàn thành nhiệm vụ", en: "complete a task", topic: "Công việc & cuộc họp" },
  { id: 60, vi: "Nộp báo cáo", en: "submit a report", topic: "Công việc & cuộc họp" },
  { id: 61, vi: "Giải quyết vấn đề", en: "solve a problem", topic: "Công việc & cuộc họp" },
  { id: 62, vi: "Hành động ngay lập tức", en: "take immediate action", topic: "Công việc & cuộc họp" },
  { id: 63, vi: "Làm theo hướng dẫn", en: "follow instructions", topic: "Công việc & cuộc họp" },
  { id: 64, vi: "Tuân thủ quy định", en: "comply with regulations", topic: "Công việc & cuộc họp" },
  { id: 65, vi: "Thực hiện biện pháp an toàn", en: "take safety precautions", topic: "Công việc & cuộc họp" },
  { id: 66, vi: "Tiến hành kiểm tra", en: "conduct an inspection", topic: "Công việc & cuộc họp" },
  { id: 67, vi: "Tiến hành bảo trì", en: "carry out maintenance", topic: "Công việc & cuộc họp" },
  { id: 68, vi: "Cải thiện năng suất", en: "improve productivity", topic: "Công việc & cuộc họp" },
  { id: 69, vi: "Giảm khối lượng công việc", en: "reduce the workload", topic: "Công việc & cuộc họp" },
  { id: 70, vi: "Phối hợp chặt chẽ với", en: "work closely with", topic: "Công việc & cuộc họp" },

  { id: 71, vi: "Đặt hàng", en: "place an order", topic: "Đơn hàng & thanh toán" },
  { id: 72, vi: "Xác nhận đơn hàng", en: "confirm an order", topic: "Đơn hàng & thanh toán" },
  { id: 73, vi: "Xử lý đơn hàng", en: "process an order", topic: "Đơn hàng & thanh toán" },
  { id: 74, vi: "Hủy đơn hàng", en: "cancel an order", topic: "Đơn hàng & thanh toán" },
  { id: 75, vi: "Theo dõi lô hàng", en: "track a shipment", topic: "Đơn hàng & thanh toán" },
  { id: 76, vi: "Ngày giao hàng dự kiến", en: "estimated delivery date", topic: "Đơn hàng & thanh toán" },
  { id: 77, vi: "Sự chậm trễ giao hàng", en: "delivery delay", topic: "Đơn hàng & thanh toán" },
  { id: 78, vi: "Còn hàng", en: "be in stock", topic: "Đơn hàng & thanh toán" },
  { id: 79, vi: "Hết hàng", en: "be out of stock", topic: "Đơn hàng & thanh toán" },
  { id: 80, vi: "Cung cấp mức giảm giá", en: "offer a discount", topic: "Đơn hàng & thanh toán" },
  { id: 81, vi: "Mức giá cạnh tranh", en: "competitive price", topic: "Đơn hàng & thanh toán" },
  { id: 82, vi: "Phí bổ sung", en: "additional fee", topic: "Đơn hàng & thanh toán" },
  { id: 83, vi: "Phí vận chuyển", en: "shipping charge", topic: "Đơn hàng & thanh toán" },
  { id: 84, vi: "Thực hiện thanh toán", en: "make a payment", topic: "Đơn hàng & thanh toán" },
  { id: 85, vi: "Xử lý thanh toán", en: "process a payment", topic: "Đơn hàng & thanh toán" },
  { id: 86, vi: "Số dư còn lại", en: "remaining balance", topic: "Đơn hàng & thanh toán" },
  { id: 87, vi: "Thanh toán trước hạn", en: "pay by the due date", topic: "Đơn hàng & thanh toán" },
  { id: 88, vi: "Hoàn tiền", en: "issue a refund", topic: "Đơn hàng & thanh toán" },
  { id: 89, vi: "Hoàn tiền đầy đủ", en: "refund someone in full", topic: "Đơn hàng & thanh toán" },
  { id: 90, vi: "Biên lai hợp lệ", en: "valid receipt", topic: "Đơn hàng & thanh toán" },
  { id: 91, vi: "Xuất hóa đơn", en: "issue an invoice", topic: "Đơn hàng & thanh toán" },
  { id: 92, vi: "Yêu cầu của khách hàng", en: "customer inquiry", topic: "Đơn hàng & thanh toán" },
  { id: 93, vi: "Khiếu nại của khách hàng", en: "customer complaint", topic: "Đơn hàng & thanh toán" },
  { id: 94, vi: "Xử lý khiếu nại", en: "handle a complaint", topic: "Đơn hàng & thanh toán" },
  { id: 95, vi: "Đáp ứng nhu cầu khách hàng", en: "meet customer needs", topic: "Đơn hàng & thanh toán" },

  { id: 96, vi: "Cải thiện sự hài lòng của khách hàng", en: "improve customer satisfaction", topic: "Kinh doanh & nhân sự" },
  { id: 97, vi: "Tăng doanh số", en: "increase sales", topic: "Kinh doanh & nhân sự" },
  { id: 98, vi: "Giảm chi phí vận hành", en: "reduce operating costs", topic: "Kinh doanh & nhân sự" },
  { id: 99, vi: "Tạo ra lợi nhuận", en: "generate profits", topic: "Kinh doanh & nhân sự" },
  { id: 100, vi: "Tiến hành nghiên cứu thị trường", en: "conduct market research", topic: "Kinh doanh & nhân sự" },
  { id: 101, vi: "Ra mắt sản phẩm mới", en: "launch a new product", topic: "Kinh doanh & nhân sự" },
  { id: 102, vi: "Thu hút khách hàng mới", en: "attract new customers", topic: "Kinh doanh & nhân sự" },
  { id: 103, vi: "Vị trí tuyển dụng", en: "job opening", topic: "Kinh doanh & nhân sự" },
  { id: 104, vi: "Ứng tuyển một vị trí", en: "apply for a position", topic: "Kinh doanh & nhân sự" },
  { id: 105, vi: "Kinh nghiệm liên quan", en: "relevant experience", topic: "Kinh doanh & nhân sự" },
  { id: 106, vi: "Đáp ứng yêu cầu chuyên môn", en: "meet the qualifications", topic: "Kinh doanh & nhân sự" },
  { id: 107, vi: "Tham gia buổi đào tạo", en: "attend a training session", topic: "Kinh doanh & nhân sự" },
  { id: 108, vi: "Đánh giá hiệu suất", en: "performance evaluation", topic: "Kinh doanh & nhân sự" },
  { id: 109, vi: "Giờ làm việc linh hoạt", en: "flexible working hours", topic: "Kinh doanh & nhân sự" },
  { id: 110, vi: "Làm việc từ xa", en: "work remotely", topic: "Kinh doanh & nhân sự" },
  { id: 111, vi: "Cân bằng công việc và cuộc sống", en: "work-life balance", topic: "Ý kiến & du lịch" },
  { id: 112, vi: "Đi công tác", en: "go on a business trip", topic: "Ý kiến & du lịch" },
  { id: 113, vi: "Đặt chỗ trước", en: "make a reservation", topic: "Ý kiến & du lịch" },
  { id: 114, vi: "Phương tiện giao thông công cộng", en: "public transportation", topic: "Ý kiến & du lịch" },
  { id: 115, vi: "Giao thông đông đúc", en: "heavy traffic", topic: "Ý kiến & du lịch" },
  { id: 116, vi: "Vị trí thuận tiện", en: "convenient location", topic: "Ý kiến & du lịch" },
  { id: 117, vi: "Đóng vai trò quan trọng trong", en: "play an important role in", topic: "Ý kiến & du lịch" },
  { id: 118, vi: "Có tác động tích cực đến", en: "have a positive impact on", topic: "Ý kiến & du lịch" },
  { id: 119, vi: "Tiết kiệm thời gian và tiền bạc", en: "save time and money", topic: "Ý kiến & du lịch" },
  { id: 120, vi: "Có được kinh nghiệm thực tế", en: "gain practical experience", topic: "Ý kiến & du lịch" },

  { id: 121, vi: "Khối lượng công việc nặng", en: "heavy workload", topic: "Cụm danh từ · Công việc" },
  { id: 122, vi: "Thời hạn dự án", en: "project deadline", topic: "Cụm danh từ · Công việc" },
  { id: 123, vi: "Kế hoạch làm việc", en: "work schedule", topic: "Cụm danh từ · Công việc" },
  { id: 124, vi: "Lịch làm việc hằng tuần", en: "weekly work schedule", topic: "Cụm danh từ · Công việc" },
  { id: 125, vi: "Môi trường làm việc", en: "work environment", topic: "Cụm danh từ · Công việc" },
  { id: 126, vi: "Kinh nghiệm làm việc", en: "work experience", topic: "Cụm danh từ · Công việc" },
  { id: 127, vi: "Kinh nghiệm thực tế", en: "practical experience", topic: "Cụm danh từ · Công việc" },
  { id: 128, vi: "Cơ hội việc làm", en: "job opportunity", topic: "Cụm danh từ · Công việc" },
  { id: 129, vi: "Vị trí còn trống", en: "vacant position", topic: "Cụm danh từ · Công việc" },
  { id: 130, vi: "Đơn xin việc", en: "job application", topic: "Cụm danh từ · Công việc" },
  { id: 131, vi: "Chương trình đào tạo", en: "training program", topic: "Cụm danh từ · Công việc" },
  { id: 132, vi: "Buổi đào tạo an toàn", en: "safety training session", topic: "Cụm danh từ · Công việc" },
  { id: 133, vi: "Buổi đánh giá hiệu suất", en: "performance review", topic: "Cụm danh từ · Công việc" },
  { id: 134, vi: "Mức tăng lương", en: "salary increase", topic: "Cụm danh từ · Công việc" },
  { id: 135, vi: "Phúc lợi nhân viên", en: "employee benefits", topic: "Cụm danh từ · Công việc" },
  { id: 136, vi: "Chính sách làm việc từ xa", en: "remote work policy", topic: "Cụm danh từ · Công việc" },
  { id: 137, vi: "Yêu cầu nghỉ phép", en: "leave request", topic: "Cụm danh từ · Công việc" },
  { id: 138, vi: "Chính sách công ty", en: "company policy", topic: "Cụm danh từ · Công việc" },
  { id: 139, vi: "Cuộc họp nhân viên", en: "staff meeting", topic: "Cụm danh từ · Công việc" },
  { id: 140, vi: "Chương trình cuộc họp", en: "meeting agenda", topic: "Cụm danh từ · Công việc" },

  { id: 141, vi: "Dịch vụ khách hàng", en: "customer service", topic: "Cụm danh từ · Khách hàng" },
  { id: 142, vi: "Sự hài lòng của khách hàng", en: "customer satisfaction", topic: "Cụm danh từ · Khách hàng" },
  { id: 143, vi: "Mẫu đơn khiếu nại", en: "complaint form", topic: "Cụm danh từ · Khách hàng" },
  { id: 144, vi: "Phiếu yêu cầu hỗ trợ", en: "support request", topic: "Cụm danh từ · Khách hàng" },
  { id: 145, vi: "Nhu cầu của khách hàng", en: "customer needs", topic: "Cụm danh từ · Khách hàng" },
  { id: 146, vi: "Thông tin liên hệ", en: "contact information", topic: "Cụm danh từ · Khách hàng" },
  { id: 147, vi: "Thông báo xác nhận đơn hàng", en: "order confirmation", topic: "Cụm danh từ · Khách hàng" },
  { id: 148, vi: "Đơn đặt hàng", en: "purchase order", topic: "Cụm danh từ · Khách hàng" },
  { id: 149, vi: "Lịch giao hàng", en: "delivery schedule", topic: "Cụm danh từ · Khách hàng" },
  { id: 150, vi: "Xác nhận giao hàng", en: "delivery confirmation", topic: "Cụm danh từ · Khách hàng" },
  { id: 151, vi: "Khung thời gian giao hàng", en: "delivery window", topic: "Cụm danh từ · Khách hàng" },
  { id: 152, vi: "Nhãn vận chuyển", en: "shipping label", topic: "Cụm danh từ · Khách hàng" },
  { id: 153, vi: "Phí hủy", en: "cancellation fee", topic: "Cụm danh từ · Khách hàng" },
  { id: 154, vi: "Số dư tài khoản", en: "account balance", topic: "Cụm danh từ · Khách hàng" },
  { id: 155, vi: "Hạn thanh toán", en: "payment deadline", topic: "Cụm danh từ · Khách hàng" },
  { id: 156, vi: "Biên lai thanh toán", en: "payment receipt", topic: "Cụm danh từ · Khách hàng" },
  { id: 157, vi: "Hóa đơn bán hàng", en: "sales invoice", topic: "Cụm danh từ · Khách hàng" },
  { id: 158, vi: "Khoản hoàn tiền đầy đủ", en: "full refund", topic: "Cụm danh từ · Khách hàng" },
  { id: 159, vi: "Chính sách hoàn trả", en: "return policy", topic: "Cụm danh từ · Khách hàng" },
  { id: 160, vi: "Thời hạn bảo hành", en: "warranty period", topic: "Cụm danh từ · Khách hàng" },

  { id: 161, vi: "Chiến dịch tiếp thị", en: "marketing campaign", topic: "Cụm danh từ · Kinh doanh" },
  { id: 162, vi: "Chiến lược quảng cáo", en: "advertising strategy", topic: "Cụm danh từ · Kinh doanh" },
  { id: 163, vi: "Đối tượng mục tiêu", en: "target audience", topic: "Cụm danh từ · Kinh doanh" },
  { id: 164, vi: "Nghiên cứu thị trường", en: "market research", topic: "Cụm danh từ · Kinh doanh" },
  { id: 165, vi: "Nhu cầu thị trường", en: "market demand", topic: "Cụm danh từ · Kinh doanh" },
  { id: 166, vi: "Cơ hội kinh doanh", en: "business opportunity", topic: "Cụm danh từ · Kinh doanh" },
  { id: 167, vi: "Lợi thế cạnh tranh", en: "competitive advantage", topic: "Cụm danh từ · Kinh doanh" },
  { id: 168, vi: "Chi phí vận hành", en: "operating costs", topic: "Cụm danh từ · Kinh doanh" },
  { id: 169, vi: "Doanh số bán hàng", en: "sales figures", topic: "Cụm danh từ · Kinh doanh" },
  { id: 170, vi: "Biên lợi nhuận", en: "profit margin", topic: "Cụm danh từ · Kinh doanh" },
  { id: 171, vi: "Mục tiêu dài hạn", en: "long-term goal", topic: "Cụm danh từ · Kinh doanh" },
  { id: 172, vi: "Chất lượng sản phẩm", en: "product quality", topic: "Cụm danh từ · Kinh doanh" },
  { id: 173, vi: "Chất lượng dịch vụ", en: "service quality", topic: "Cụm danh từ · Kinh doanh" },
  { id: 174, vi: "Sản phẩm mới", en: "new product", topic: "Cụm danh từ · Kinh doanh" },

  { id: 175, vi: "Thiết bị văn phòng", en: "office equipment", topic: "Cụm danh từ · Kỹ thuật" },
  { id: 176, vi: "Sự cố kỹ thuật", en: "technical issue", topic: "Cụm danh từ · Kỹ thuật" },
  { id: 177, vi: "Lỗi hệ thống", en: "system error", topic: "Cụm danh từ · Kỹ thuật" },
  { id: 178, vi: "Báo cáo kiểm tra", en: "inspection report", topic: "Cụm danh từ · Kỹ thuật" },
  { id: 179, vi: "Lịch bảo trì", en: "maintenance schedule", topic: "Cụm danh từ · Kỹ thuật" },
  { id: 180, vi: "Hệ thống giao thông", en: "transportation system", topic: "Cụm danh từ · Kỹ thuật" },

  { id: 181, vi: "Trả lời email", en: "reply to an email", topic: "Email nâng cao" },
  { id: 182, vi: "Chuyển tiếp email", en: "forward an email", topic: "Email nâng cao" },
  { id: 183, vi: "Gửi lời nhắc", en: "send a reminder", topic: "Email nâng cao" },
  { id: 184, vi: "Yêu cầu xác nhận", en: "request confirmation", topic: "Email nâng cao" },
  { id: 185, vi: "Xác nhận lịch hẹn", en: "confirm an appointment", topic: "Email nâng cao" },
  { id: 186, vi: "Sắp xếp một cuộc gặp", en: "arrange a meeting", topic: "Email nâng cao" },
  { id: 187, vi: "Hoãn cuộc họp", en: "postpone a meeting", topic: "Email nâng cao" },
  { id: 188, vi: "Tham gia cuộc gọi hội nghị", en: "join a conference call", topic: "Email nâng cao" },
  { id: 189, vi: "Để lại lời nhắn", en: "leave a message", topic: "Email nâng cao" },
  { id: 190, vi: "Gọi điện lại", en: "return a phone call", topic: "Email nâng cao" },
  { id: 191, vi: "Đưa ra yêu cầu tìm hiểu", en: "make an inquiry", topic: "Email nâng cao" },
  { id: 192, vi: "Phản hồi một yêu cầu", en: "respond to an inquiry", topic: "Email nâng cao" },
  { id: 193, vi: "Gửi đơn khiếu nại", en: "file a complaint", topic: "Email nâng cao" },
  { id: 194, vi: "Đưa ra đề xuất", en: "make a suggestion", topic: "Email nâng cao" },
  { id: 195, vi: "Chấp nhận đề xuất", en: "accept a suggestion", topic: "Email nâng cao" },
  { id: 196, vi: "Đưa ra khuyến nghị", en: "make a recommendation", topic: "Email nâng cao" },
  { id: 197, vi: "Thông báo chính thức", en: "give notice", topic: "Email nâng cao" },
  { id: 198, vi: "Cung cấp thông tin cập nhật", en: "provide an update", topic: "Email nâng cao" },
  { id: 199, vi: "Làm rõ hiểu lầm", en: "clarify a misunderstanding", topic: "Email nâng cao" },
  { id: 200, vi: "Giải quyết tranh chấp", en: "resolve a dispute", topic: "Email nâng cao" },
  { id: 201, vi: "Bày tỏ sự cảm kích", en: "express appreciation", topic: "Email nâng cao" },
  { id: 202, vi: "Gửi lời mời", en: "extend an invitation", topic: "Email nâng cao" },
  { id: 203, vi: "Chấp nhận lời mời", en: "accept an invitation", topic: "Email nâng cao" },
  { id: 204, vi: "Từ chối lời mời", en: "decline an invitation", topic: "Email nâng cao" },
  { id: 205, vi: "Đáp ứng một yêu cầu", en: "accommodate a request", topic: "Email nâng cao" },
  { id: 206, vi: "Xin gia hạn", en: "ask for an extension", topic: "Email nâng cao" },
  { id: 207, vi: "Cho phép gia hạn", en: "grant an extension", topic: "Email nâng cao" },
  { id: 208, vi: "Gửi email xác nhận", en: "send a confirmation email", topic: "Email nâng cao" },
  { id: 209, vi: "Đính kèm tài liệu bắt buộc", en: "attach the required documents", topic: "Email nâng cao" },
  { id: 210, vi: "Cập nhật thông tin liên hệ", en: "update contact details", topic: "Email nâng cao" },

  { id: 211, vi: "Giao nhiệm vụ", en: "assign a task", topic: "Vận hành công việc" },
  { id: 212, vi: "Phân công trách nhiệm", en: "delegate responsibilities", topic: "Vận hành công việc" },
  { id: 213, vi: "Đặt mức độ ưu tiên", en: "set priorities", topic: "Vận hành công việc" },
  { id: 214, vi: "Đạt được mục tiêu", en: "achieve a target", topic: "Vận hành công việc" },
  { id: 215, vi: "Theo dõi tiến độ", en: "monitor progress", topic: "Vận hành công việc" },
  { id: 216, vi: "Xem xét hiệu suất", en: "review performance", topic: "Vận hành công việc" },
  { id: 217, vi: "Đánh giá kết quả", en: "evaluate the results", topic: "Vận hành công việc" },
  { id: 218, vi: "Đáp ứng kỳ vọng", en: "meet expectations", topic: "Vận hành công việc" },
  { id: 219, vi: "Vượt quá kỳ vọng", en: "exceed expectations", topic: "Vận hành công việc" },
  { id: 220, vi: "Cung cấp đào tạo", en: "provide training", topic: "Vận hành công việc" },
  { id: 221, vi: "Phát triển chiến lược", en: "develop a strategy", topic: "Vận hành công việc" },
  { id: 222, vi: "Thực hiện kế hoạch", en: "implement a plan", topic: "Vận hành công việc" },
  { id: 223, vi: "Chỉnh sửa đề xuất", en: "revise a proposal", topic: "Vận hành công việc" },
  { id: 224, vi: "Phê duyệt đề xuất", en: "approve a proposal", topic: "Vận hành công việc" },
  { id: 225, vi: "Từ chối đề xuất", en: "reject a proposal", topic: "Vận hành công việc" },
  { id: 226, vi: "Ký hợp đồng", en: "sign a contract", topic: "Vận hành công việc" },
  { id: 227, vi: "Gia hạn hợp đồng", en: "renew a contract", topic: "Vận hành công việc" },
  { id: 228, vi: "Chấm dứt hợp đồng", en: "terminate a contract", topic: "Vận hành công việc" },
  { id: 229, vi: "Đàm phán các điều khoản", en: "negotiate the terms", topic: "Vận hành công việc" },
  { id: 230, vi: "Phân bổ nguồn lực", en: "allocate resources", topic: "Vận hành công việc" },
  { id: 231, vi: "Quản lý ngân sách", en: "manage a budget", topic: "Vận hành công việc" },
  { id: 232, vi: "Cắt giảm chi phí", en: "cut expenses", topic: "Vận hành công việc" },
  { id: 233, vi: "Lưu giữ hồ sơ", en: "keep records", topic: "Vận hành công việc" },
  { id: 234, vi: "Cập nhật cơ sở dữ liệu", en: "update a database", topic: "Vận hành công việc" },
  { id: 235, vi: "Truy cập hệ thống", en: "access the system", topic: "Vận hành công việc" },
  { id: 236, vi: "Cài đặt phần mềm", en: "install software", topic: "Vận hành công việc" },
  { id: 237, vi: "Nâng cấp thiết bị", en: "upgrade equipment", topic: "Vận hành công việc" },
  { id: 238, vi: "Thay thế thiết bị", en: "replace equipment", topic: "Vận hành công việc" },
  { id: 239, vi: "Sửa chữa thiết bị", en: "repair equipment", topic: "Vận hành công việc" },
  { id: 240, vi: "Báo cáo sự cố", en: "report a malfunction", topic: "Vận hành công việc" },
  { id: 241, vi: "Đảm bảo an toàn", en: "ensure safety", topic: "Vận hành công việc" },
  { id: 242, vi: "Ngăn ngừa tai nạn", en: "prevent accidents", topic: "Vận hành công việc" },
  { id: 243, vi: "Tuân theo quy trình", en: "follow a procedure", topic: "Vận hành công việc" },
  { id: 244, vi: "Duy trì tiêu chuẩn chất lượng", en: "maintain quality standards", topic: "Vận hành công việc" },
  { id: 245, vi: "Nâng cao tinh thần nhân viên", en: "boost employee morale", topic: "Vận hành công việc" },

  { id: 246, vi: "Cải thiện giao tiếp", en: "improve communication", topic: "Bán hàng & dịch vụ" },
  { id: 247, vi: "Cung cấp dịch vụ xuất sắc", en: "provide excellent service", topic: "Bán hàng & dịch vụ" },
  { id: 248, vi: "Xây dựng lòng trung thành của khách hàng", en: "build customer loyalty", topic: "Bán hàng & dịch vụ" },
  { id: 249, vi: "Giữ chân khách hàng hiện tại", en: "retain existing customers", topic: "Bán hàng & dịch vụ" },
  { id: 250, vi: "Thu hút khách hàng tiềm năng", en: "attract potential customers", topic: "Bán hàng & dịch vụ" },
  { id: 251, vi: "Xử lý yêu cầu của khách hàng", en: "handle customer requests", topic: "Bán hàng & dịch vụ" },
  { id: 252, vi: "Giải quyết vấn đề của khách hàng", en: "resolve a customer issue", topic: "Bán hàng & dịch vụ" },
  { id: 253, vi: "Xử lý khoản hoàn tiền", en: "process a refund", topic: "Bán hàng & dịch vụ" },
  { id: 254, vi: "Đổi một mặt hàng", en: "exchange an item", topic: "Bán hàng & dịch vụ" },
  { id: 255, vi: "Trả lại sản phẩm", en: "return a product", topic: "Bán hàng & dịch vụ" },
  { id: 256, vi: "Đề nghị sản phẩm thay thế", en: "offer a replacement", topic: "Bán hàng & dịch vụ" },
  { id: 257, vi: "Xác nhận đặt chỗ", en: "confirm a reservation", topic: "Bán hàng & dịch vụ" },
  { id: 258, vi: "Thay đổi đặt chỗ", en: "modify a reservation", topic: "Bán hàng & dịch vụ" },
  { id: 259, vi: "Hủy đặt chỗ", en: "cancel a reservation", topic: "Bán hàng & dịch vụ" },
  { id: 260, vi: "Kiểm tra tình trạng còn chỗ", en: "check availability", topic: "Bán hàng & dịch vụ" },
  { id: 261, vi: "Xác nhận tình trạng còn chỗ", en: "confirm availability", topic: "Bán hàng & dịch vụ" },
  { id: 262, vi: "Thực hiện giao hàng", en: "make a delivery", topic: "Bán hàng & dịch vụ" },
  { id: 263, vi: "Sắp xếp giao hàng", en: "arrange delivery", topic: "Bán hàng & dịch vụ" },
  { id: 264, vi: "Nhận hàng giao", en: "receive a delivery", topic: "Bán hàng & dịch vụ" },
  { id: 265, vi: "Vận chuyển hàng hóa", en: "ship goods", topic: "Bán hàng & dịch vụ" },
  { id: 266, vi: "Đóng gói các mặt hàng", en: "pack the items", topic: "Bán hàng & dịch vụ" },
  { id: 267, vi: "Quản lý hàng tồn kho", en: "manage inventory", topic: "Bán hàng & dịch vụ" },
  { id: 268, vi: "Bổ sung hàng tồn kho", en: "replenish stock", topic: "Bán hàng & dịch vụ" },
  { id: 269, vi: "Trưng bày hàng hóa", en: "display merchandise", topic: "Bán hàng & dịch vụ" },
  { id: 270, vi: "So sánh giá", en: "compare prices", topic: "Bán hàng & dịch vụ" },
  { id: 271, vi: "Thương lượng giá", en: "negotiate a price", topic: "Bán hàng & dịch vụ" },
  { id: 272, vi: "Cung cấp chương trình khuyến mãi đặc biệt", en: "offer a special promotion", topic: "Bán hàng & dịch vụ" },
  { id: 273, vi: "Đạt mục tiêu doanh số", en: "meet a sales target", topic: "Bán hàng & dịch vụ" },
  { id: 274, vi: "Tăng thị phần", en: "increase market share", topic: "Bán hàng & dịch vụ" },
  { id: 275, vi: "Giành được lòng tin của khách hàng", en: "gain customer trust", topic: "Bán hàng & dịch vụ" },

  { id: 276, vi: "Bảo vệ thông tin cá nhân", en: "protect personal information", topic: "Ý kiến & phát triển" },
  { id: 277, vi: "Tạo cơ hội việc làm", en: "create job opportunities", topic: "Ý kiến & phát triển" },
  { id: 278, vi: "Cải thiện mức sống", en: "improve living standards", topic: "Ý kiến & phát triển" },
  { id: 279, vi: "Thúc đẩy tăng trưởng kinh tế", en: "promote economic growth", topic: "Ý kiến & phát triển" },
  { id: 280, vi: "Bảo vệ môi trường", en: "protect the environment", topic: "Ý kiến & phát triển" },
  { id: 281, vi: "Giảm chất thải", en: "reduce waste", topic: "Ý kiến & phát triển" },
  { id: 282, vi: "Tiết kiệm năng lượng", en: "save energy", topic: "Ý kiến & phát triển" },
  { id: 283, vi: "Sử dụng tài nguyên hiệu quả", en: "use resources efficiently", topic: "Ý kiến & phát triển" },
  { id: 284, vi: "Phát triển kỹ năng giao tiếp", en: "develop communication skills", topic: "Ý kiến & phát triển" },
  { id: 285, vi: "Cải thiện kỹ năng giải quyết vấn đề", en: "improve problem-solving skills", topic: "Ý kiến & phát triển" },
  { id: 286, vi: "Mở rộng kiến thức", en: "broaden one’s knowledge", topic: "Ý kiến & phát triển" },
  { id: 287, vi: "Xây dựng sự tự tin", en: "build confidence", topic: "Ý kiến & phát triển" },
  { id: 288, vi: "Làm việc độc lập", en: "work independently", topic: "Ý kiến & phát triển" },
  { id: 289, vi: "Làm việc theo nhóm", en: "work as part of a team", topic: "Ý kiến & phát triển" },
  { id: 290, vi: "Tạo ấn tượng tốt", en: "make a good impression", topic: "Ý kiến & phát triển" },
  { id: 291, vi: "Duy trì cân bằng công việc và cuộc sống", en: "maintain a work-life balance", topic: "Ý kiến & phát triển" },
  { id: 292, vi: "Đối phó với căng thẳng", en: "cope with stress", topic: "Ý kiến & phát triển" },
  { id: 293, vi: "Thích nghi với sự thay đổi", en: "adapt to change", topic: "Ý kiến & phát triển" },
  { id: 294, vi: "Tận dụng cơ hội", en: "take advantage of an opportunity", topic: "Ý kiến & phát triển" },
  { id: 295, vi: "Sắp xếp chuyến đi", en: "make travel arrangements", topic: "Ý kiến & phát triển" },
  { id: 296, vi: "Kịp chuyến bay", en: "catch a flight", topic: "Ý kiến & phát triển" },
  { id: 297, vi: "Lên máy bay", en: "board a plane", topic: "Ý kiến & phát triển" },
  { id: 298, vi: "Làm thủ tục nhận phòng", en: "check into a hotel", topic: "Ý kiến & phát triển" },
  { id: 299, vi: "Làm thủ tục trả phòng", en: "check out of a hotel", topic: "Ý kiến & phát triển" },
  { id: 300, vi: "Đi làm hằng ngày", en: "commute to work", topic: "Ý kiến & phát triển" },

  { id: 301, vi: "Tình trạng ùn tắc giao thông", en: "traffic congestion", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 302, vi: "Sự phát triển nghề nghiệp", en: "career development", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 303, vi: "Sự thăng tiến nghề nghiệp", en: "career advancement", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 304, vi: "Sự hài lòng trong công việc", en: "job satisfaction", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 305, vi: "Hiệu suất nhân viên", en: "employee performance", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 306, vi: "Năng suất nhân viên", en: "employee productivity", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 307, vi: "Khả năng giữ chân nhân viên", en: "employee retention", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 308, vi: "Tình trạng thiếu nhân sự", en: "staff shortage", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 309, vi: "Chi phí lao động", en: "labor costs", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 310, vi: "Mức lương hằng năm", en: "annual salary", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 311, vi: "Khoảng lương", en: "salary range", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 312, vi: "Thời gian thử việc", en: "probationary period", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 313, vi: "Vị trí toàn thời gian", en: "full-time position", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 314, vi: "Vị trí bán thời gian", en: "part-time position", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 315, vi: "Vị trí dành cho người mới", en: "entry-level position", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 316, vi: "Vị trí quản lý", en: "management position", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 317, vi: "Ứng viên đủ năng lực", en: "qualified applicant", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 318, vi: "Mô tả công việc", en: "job description", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 319, vi: "Yêu cầu công việc", en: "job requirements", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 320, vi: "Hạn nộp đơn", en: "application deadline", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 321, vi: "Quy trình phỏng vấn", en: "interview process", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 322, vi: "Tài liệu đào tạo", en: "training materials", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 323, vi: "Lịch đào tạo", en: "training schedule", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 324, vi: "Nguồn lực công ty", en: "company resources", topic: "Cụm danh từ · Phát triển nghề nghiệp" },
  { id: 325, vi: "Vật tư văn phòng", en: "office supplies", topic: "Cụm danh từ · Phát triển nghề nghiệp" },

  { id: 326, vi: "Trưởng nhóm", en: "team leader", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 327, vi: "Đề xuất dự án", en: "project proposal", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 328, vi: "Quản lý dự án", en: "project manager", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 329, vi: "Ngân sách dự án", en: "project budget", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 330, vi: "Yêu cầu dự án", en: "project requirements", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 331, vi: "Tiến độ dự án", en: "project timeline", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 332, vi: "Báo cáo tiến độ", en: "progress report", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 333, vi: "Thông tin cập nhật tình hình", en: "status update", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 334, vi: "Phòng họp", en: "meeting room", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 335, vi: "Cuộc gọi hội nghị", en: "conference call", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 336, vi: "Cuộc họp kinh doanh", en: "business meeting", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 337, vi: "Cuộc họp phòng ban", en: "department meeting", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 338, vi: "Hội nghị thường niên", en: "annual conference", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 339, vi: "Tiêu chuẩn chất lượng", en: "quality standards", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 340, vi: "Quy định an toàn", en: "safety regulations", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 341, vi: "Thiết bị an toàn", en: "safety equipment", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 342, vi: "Lối thoát hiểm", en: "emergency exit", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 343, vi: "Hệ thống an ninh", en: "security system", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 344, vi: "Công việc bảo trì", en: "maintenance work", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 345, vi: "Chi phí bảo trì", en: "maintenance costs", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 346, vi: "Hỗ trợ kỹ thuật", en: "technical support", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 347, vi: "Hệ thống máy tính", en: "computer system", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 348, vi: "Bản cập nhật phần mềm", en: "software update", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 349, vi: "Sự cố thiết bị", en: "equipment failure", topic: "Cụm danh từ · Dự án & vận hành" },
  { id: 350, vi: "Quy trình sản xuất", en: "production process", topic: "Cụm danh từ · Dự án & vận hành" },

  { id: 351, vi: "Cơ sở sản xuất", en: "manufacturing facility", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 352, vi: "Lòng trung thành của khách hàng", en: "customer loyalty", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 353, vi: "Phản hồi của khách hàng", en: "customer feedback", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 354, vi: "Cơ sở dữ liệu khách hàng", en: "customer database", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 355, vi: "Tài khoản khách hàng", en: "customer account", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 356, vi: "Nhân viên dịch vụ", en: "service representative", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 357, vi: "Bộ phận dịch vụ", en: "service department", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 358, vi: "Phí dịch vụ", en: "service fee", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 359, vi: "Ưu đãi đặc biệt", en: "special offer", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 360, vi: "Tỷ lệ giảm giá", en: "discount rate", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 361, vi: "Giá khuyến mãi", en: "sale price", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 362, vi: "Giá bán lẻ", en: "retail price", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 363, vi: "Mô tả sản phẩm", en: "product description", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 364, vi: "Tính năng sản phẩm", en: "product features", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 365, vi: "Tình trạng sẵn có của sản phẩm", en: "product availability", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 366, vi: "Bảo hành sản phẩm", en: "product warranty", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 367, vi: "Mã đơn hàng", en: "order number", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 368, vi: "Trạng thái đơn hàng", en: "order status", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 369, vi: "Địa chỉ giao hàng", en: "delivery address", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 370, vi: "Dịch vụ giao hàng", en: "delivery service", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 371, vi: "Phí giao hàng", en: "delivery fee", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 372, vi: "Địa chỉ vận chuyển", en: "shipping address", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 373, vi: "Phương thức vận chuyển", en: "shipping method", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 374, vi: "Phương thức thanh toán", en: "payment method", topic: "Cụm danh từ · Bán hàng & logistics" },
  { id: 375, vi: "Thanh toán bằng thẻ tín dụng", en: "credit card payment", topic: "Cụm danh từ · Bán hàng & logistics" },

  { id: 376, vi: "Thông tin thanh toán", en: "billing information", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 377, vi: "Tăng trưởng kinh doanh", en: "business growth", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 378, vi: "Chiến lược kinh doanh", en: "business strategy", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 379, vi: "Mối quan hệ kinh doanh", en: "business relationship", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 380, vi: "Đối tác kinh doanh", en: "business partner", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 381, vi: "Doanh thu hằng năm", en: "annual revenue", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 382, vi: "Chi phí hằng tháng", en: "monthly expenses", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 383, vi: "Báo cáo tài chính", en: "financial report", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 384, vi: "Kế hoạch ngân sách", en: "budget plan", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 385, vi: "Ngân sách quảng cáo", en: "advertising budget", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 386, vi: "Hình ảnh thương hiệu", en: "brand image", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 387, vi: "Danh tiếng thương hiệu", en: "brand reputation", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 388, vi: "Thị phần", en: "market share", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 389, vi: "Xu hướng thị trường", en: "market trend", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 390, vi: "Tăng trưởng kinh tế", en: "economic growth", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 391, vi: "Tác động môi trường", en: "environmental impact", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 392, vi: "Mức tiêu thụ năng lượng", en: "energy consumption", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 393, vi: "Cơ sở vật chất công cộng", en: "public facilities", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 394, vi: "Chi phí vận chuyển", en: "transportation costs", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 395, vi: "Chi phí đi lại", en: "travel expenses", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 396, vi: "Lịch trình chuyến đi", en: "travel itinerary", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 397, vi: "Đặt phòng khách sạn", en: "hotel reservation", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 398, vi: "Chỗ ở khách sạn", en: "hotel accommodation", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 399, vi: "Lịch bay", en: "flight schedule", topic: "Cụm danh từ · Kinh doanh & du lịch" },
  { id: 400, vi: "Giờ khởi hành", en: "departure time", topic: "Cụm danh từ · Kinh doanh & du lịch" },
];

type StudyItem = {
  vi: string;
  en: string;
  note?: string;
};

const makeVerbPatterns = (
  startId: number,
  pattern: string,
  topic: string,
  items: StudyItem[],
): Collocation[] => items.map((item, index) => ({
  ...item,
  id: startId + index,
  topic,
  kind: "verb-pattern",
  pattern,
}));

const makePrepositions = (
  startId: number,
  topic: string,
  items: StudyItem[],
): Collocation[] => items.map((item, index) => ({
  ...item,
  id: startId + index,
  topic,
  kind: "preposition",
}));

const verbToInfinitive = makeVerbPatterns(401, "___ + to V", "V-pattern · V + to V", [
  { vi: "đồng ý làm gì", en: "agree" },
  { vi: "sắp xếp để làm gì", en: "arrange" },
  { vi: "quyết định làm gì", en: "decide" },
  { vi: "mong đợi làm gì", en: "expect" },
  { vi: "không làm được việc gì", en: "fail" },
  { vi: "hy vọng làm gì", en: "hope" },
  { vi: "học cách làm gì", en: "learn" },
  { vi: "xoay xở làm được gì", en: "manage" },
  { vi: "cần làm gì", en: "need" },
  { vi: "đề nghị làm gì", en: "offer" },
  { vi: "lên kế hoạch làm gì", en: "plan" },
  { vi: "chuẩn bị làm gì", en: "prepare" },
  { vi: "hứa làm gì", en: "promise" },
  { vi: "từ chối làm gì", en: "refuse" },
  { vi: "có vẻ làm gì", en: "seem" },
  { vi: "muốn làm gì", en: "want" },
]);

const verbGerund = makeVerbPatterns(417, "___ + V-ing", "V-pattern · V + V-ing", [
  { vi: "thừa nhận đã làm gì", en: "admit" },
  { vi: "đề xuất làm gì", en: "suggest", note: "suggest + V-ing; hoặc suggest that + S + V" },
  { vi: "khuyến nghị làm gì", en: "recommend", note: "recommend + V-ing; hoặc recommend that + S + V" },
  { vi: "tránh làm gì", en: "avoid", note: "Không dùng avoid + to V." },
  { vi: "trì hoãn làm gì", en: "delay" },
  { vi: "hoãn làm gì", en: "postpone" },
  { vi: "nhớ hoặc tiếc việc từng làm", en: "miss" },
  { vi: "thích làm gì", en: "enjoy" },
  { vi: "phiền khi làm gì", en: "mind" },
  { vi: "hoàn thành việc gì", en: "finish" },
  { vi: "tiếp tục làm gì", en: "keep" },
  { vi: "luyện tập làm gì", en: "practice" },
  { vi: "cân nhắc làm gì", en: "consider" },
  { vi: "thảo luận việc làm gì", en: "discuss" },
  { vi: "có nguy cơ làm gì", en: "risk" },
]);

const verbObjectInfinitive = makeVerbPatterns(432, "___ + O + to V", "V-pattern · V + O + to V", [
  { vi: "khuyên ai làm gì", en: "advise" },
  { vi: "nhắc ai làm gì", en: "remind" },
  { vi: "chỉ dẫn hoặc yêu cầu ai làm gì", en: "instruct" },
  { vi: "cho phép ai làm gì", en: "allow" },
  { vi: "tạo điều kiện cho ai làm gì", en: "enable" },
  { vi: "khuyến khích ai làm gì", en: "encourage" },
  { vi: "tạo động lực cho ai làm gì", en: "motivate" },
  { vi: "yêu cầu hoặc nhờ ai làm gì", en: "ask" },
  { vi: "yêu cầu ai phải làm gì", en: "require" },
  { vi: "mời ai làm gì", en: "invite" },
  { vi: "buộc ai làm gì", en: "force" },
  { vi: "khiến ai hoặc điều gì làm gì", en: "cause" },
  { vi: "mong đợi ai làm gì", en: "expect" },
  { vi: "muốn ai làm gì", en: "want" },
  { vi: "cần ai làm gì", en: "need" },
]);

const verbPrepositions = makePrepositions(447, "Giới từ · Verb + preposition", [
  { vi: "ứng tuyển hoặc nộp đơn xin", en: "apply for" },
  { vi: "xin lỗi vì", en: "apologize for" },
  { vi: "đồng ý với một người hoặc ý kiến", en: "agree with", note: "agree with + người/ý kiến" },
  { vi: "thống nhất về một vấn đề hoặc kế hoạch", en: "agree on", note: "agree on + vấn đề/kế hoạch" },
  { vi: "tìm kiếm", en: "look for" },
  { vi: "thuộc về", en: "belong to" },
  { vi: "phàn nàn về", en: "complain about" },
  { vi: "tập trung vào", en: "focus/concentrate on" },
  { vi: "bao gồm, được cấu thành từ", en: "consist of" },
  { vi: "dành tiền hoặc thời gian cho", en: "spend on", note: "spend money/time on + N/V-ing; không dùng spend for." },
  { vi: "đóng góp hoặc góp phần vào", en: "contribute to" },
  { vi: "phụ thuộc vào", en: "depend on" },
  { vi: "tham gia vào", en: "participate in" },
  { vi: "đề cập hoặc tham chiếu đến", en: "refer to" },
  { vi: "trả tiền cho", en: "pay for" },
  { vi: "dẫn đến một kết quả", en: "result in" },
  { vi: "thành công trong", en: "succeed in" },
  { vi: "chờ đợi", en: "wait for" },
  { vi: "chuẩn bị cho", en: "prepare for" },
  { vi: "giao tiếp hoặc liên lạc với", en: "communicate with" },
]);

const objectPrepositions = makePrepositions(467, "Giới từ · V + O + preposition", [
  { vi: "cung cấp B cho A", en: "provide A with B" },
  { vi: "thông báo cho A về B", en: "inform A of/about B" },
  { vi: "nhắc A nhớ về B", en: "remind A of B" },
  { vi: "cảm ơn A vì B", en: "thank A for B" },
  { vi: "ngăn A làm gì", en: "prevent A from V-ing", note: "Sau from dùng V-ing." },
  { vi: "bảo vệ A khỏi B", en: "protect A from B" },
  { vi: "tính phí A cho B", en: "charge A for B" },
  { vi: "mời A đến B", en: "invite A to B", note: "invite A to + sự kiện/địa điểm; invite A to V khi mời ai làm gì." },
]);

const prepositionalTo = makePrepositions(475, "Giới từ · To + V-ing", [
  { vi: "cam kết làm gì", en: "be committed to + V-ing", note: "to là giới từ, vì vậy theo sau bằng V-ing/N." },
  { vi: "quen với việc làm gì", en: "be used to + V-ing", note: "Khác used to + V: từng làm gì trong quá khứ." },
  { vi: "phản đối việc làm gì", en: "be opposed to + V-ing" },
  { vi: "phải chịu hoặc tuân theo", en: "be subject to + N/V-ing" },
  { vi: "mong chờ làm gì", en: "look forward to + V-ing" },
  { vi: "phản đối việc làm gì", en: "object to + V-ing" },
  { vi: "góp phần vào việc làm gì", en: "contribute to + V-ing" },
  { vi: "dẫn đến việc làm gì", en: "lead to + V-ing" },
  { vi: "cống hiến bản thân cho việc gì", en: "dedicate oneself to + V-ing" },
  { vi: "phải dùng đến biện pháp làm gì", en: "resort to + V-ing" },
]);

const writingPrepositions = makePrepositions(485, "Giới từ · Cụm Writing", [
  { vi: "trước, báo hoặc làm sớm hơn", en: "in advance" },
  { vi: "đầy đủ, toàn bộ", en: "in full" },
  { vi: "trực tiếp, đích thân", en: "in person" },
  { vi: "một cách chi tiết", en: "in detail" },
  { vi: "đang được tiến hành", en: "in progress" },
  { vi: "đã sẵn sàng hoặc đã được thiết lập", en: "in place" },
  { vi: "với số lượng lớn", en: "in bulk" },
  { vi: "nói chung", en: "in general" },
  { vi: "ngoài việc, bên cạnh việc", en: "in addition to + N/V-ing" },
  { vi: "ngoài ra hoặc ngoại trừ", en: "apart from + N/V-ing" },
  { vi: "thay vì", en: "instead of + N/V-ing" },
  { vi: "do, bởi vì", en: "due to + N/V-ing" },
  { vi: "do, bởi vì (trang trọng)", en: "owing to + N/V-ing" },
  { vi: "bởi vì", en: "because of + N/V-ing" },
  { vi: "nhằm mục đích làm gì", en: "with a view to + V-ing", note: "to là giới từ, không dùng to V." },
  { vi: "trước một mốc hoặc sự kiện", en: "prior to + N/V-ing" },
  { vi: "được lên lịch để làm gì", en: "be scheduled to + V", note: "Ở đây to mở đầu động từ nguyên mẫu." },
  { vi: "được xem là + tính từ hoặc danh từ", en: "be deemed + adjective/noun" },
  { vi: "được đánh giá là sẽ làm gì", en: "be judged to + V" },
  { vi: "mà phải chịu hoặc tuân theo", en: "which is subject to + N" },
  { vi: "xảy ra hoặc có hiệu lực trước", en: "be prior to + N/V-ing" },
]);

type IdeaRoute = {
  title: string;
  chunks: [string, string, string, string, string];
};

const speakingRoutes: IdeaRoute[] = [
  {
    title: "Time & productivity",
    chunks: ["save time", "focus on important tasks", "complete tasks more quickly", "reduce delays", "improve productivity"],
  },
  {
    title: "Money & value",
    chunks: ["reduce unnecessary costs", "control spending more effectively", "spend money on higher priorities", "get better long-term value", "improve financial stability"],
  },
  {
    title: "Stress & performance",
    chunks: ["reduce daily stress", "stay mentally refreshed", "concentrate better", "make fewer mistakes", "improve overall performance"],
  },
  {
    title: "Better decisions",
    chunks: ["access reliable information", "compare different alternatives", "evaluate advantages and disadvantages", "make informed decisions", "avoid poor choices"],
  },
  {
    title: "Practical experience",
    chunks: ["gain practical experience", "apply theory to real situations", "develop useful skills", "build confidence", "prepare for future work"],
  },
  {
    title: "Communication",
    chunks: ["exchange ideas openly", "hear different viewpoints", "understand one another better", "avoid misunderstandings", "strengthen relationships"],
  },
  {
    title: "Teamwork",
    chunks: ["combine different strengths", "divide responsibilities clearly", "support one another", "solve problems faster", "achieve shared goals"],
  },
  {
    title: "Career growth",
    chunks: ["meet experienced professionals", "build valuable connections", "learn about new opportunities", "strengthen a professional profile", "expand career opportunities"],
  },
  {
    title: "Motivation",
    chunks: ["set clear and realistic goals", "track progress regularly", "stay motivated", "maintain consistent effort", "achieve better results"],
  },
  {
    title: "Flexibility",
    chunks: ["have more choices", "adapt to personal needs", "manage time more flexibly", "handle responsibilities more easily", "improve quality of life"],
  },
  {
    title: "Health & energy",
    chunks: ["get enough rest and exercise", "restore energy", "sharpen concentration", "maintain consistent performance", "protect long-term health"],
  },
  {
    title: "Safety",
    chunks: ["identify possible risks early", "follow proper procedures", "prevent mistakes and accidents", "protect people and property", "reduce delays and costs"],
  },
  {
    title: "Environment",
    chunks: ["use fewer resources", "create less waste", "lower pollution", "protect the natural environment", "improve community quality of life"],
  },
  {
    title: "Creativity",
    chunks: ["consider different perspectives", "think more critically", "generate practical ideas", "find better solutions", "support innovation"],
  },
  {
    title: "Learning",
    chunks: ["focus on weak areas", "correct mistakes", "remember information longer", "improve knowledge and skills", "become a more independent learner"],
  },
  {
    title: "Customer service",
    chunks: ["understand customer needs", "respond quickly and clearly", "provide better service", "build customer trust", "increase satisfaction and loyalty"],
  },
  {
    title: "Work-life balance",
    chunks: ["set reasonable workloads", "allow enough recovery time", "reduce stress and burnout", "increase job satisfaction", "retain skilled employees"],
  },
  {
    title: "Relationships",
    chunks: ["spend quality time together", "communicate openly", "understand each other's feelings", "provide mutual support", "build stronger relationships"],
  },
];

const speakingChunks: Collocation[] = speakingRoutes.flatMap((route, routeIndex) =>
  route.chunks.slice(0, -1).map((_, stepIndex) => ({
    id: 506 + routeIndex * 4 + stepIndex,
    vi: route.title,
    en: route.chunks[stepIndex + 1],
    topic: `Speaking Sprint · ${route.title}`,
    kind: "speaking" as const,
    pattern: `${route.chunks.slice(0, stepIndex + 1).join(" → ")} → ___`,
    note: "Say the complete chain aloud before the next question appears.",
    chunkStep: stepIndex + 1,
  })),
);

export const collocations: Collocation[] = [
  ...baseCollocations,
  ...verbToInfinitive,
  ...verbGerund,
  ...verbObjectInfinitive,
  ...verbPrepositions,
  ...objectPrepositions,
  ...prepositionalTo,
  ...writingPrepositions,
  ...speakingChunks,
];
